spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://140.143.73.74:3306/formu
#    url: jdbc:mysql://localhost:3306/formu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
    host: 140.143.73.74
#    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    password: 123
  mail:
    host: smtp.qq.com
    username: 280803590@qq.com
    password: xxkjnzuhaxvubheb
    port: 587
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


server:
  port: 8088
